In [46]:
%run Network

AttributeError: 'NeuronInput' object has no attribute 'init_children'

In [19]:
import numpy as np
for i in range(10):
    print(np.random.randint(0,2,2))    

[0 0]
[1 0]
[0 1]
[0 0]
[1 1]
[1 0]
[1 0]
[1 1]
[0 0]
[1 1]


In [34]:
import numpy as np
a = np.array([
    [[5,3],[1,2]],
    [[6,7],[4,0]]
]
        )
a.sum()
a = 1/(a+0.0001)
print(a)
tmp = np.random.rand()


[[[  1.99996000e-01   3.33322223e-01]
  [  9.99900010e-01   4.99975001e-01]]

 [[  1.66663889e-01   1.42855102e-01]
  [  2.49993750e-01   1.00000000e+04]]]


In [50]:
import numpy as np
a = np.array([np.inf, 1,2,3])
a = 1/a
print(a)

[ 0.          1.          0.5         0.33333333]
